name: bigfanvoicechat
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

  # State Management
  provider: ^6.1.1

  # Storage & Preferences
  shared_preferences: ^2.2.2

  # Network & API
  http: ^1.1.2

  # Voice Chat
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.1.0

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
