name: bigfun_voice
description: A new Flutter project for BigFun Voice Chat
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core (required for Firestore)
  firebase_core: ^3.6.0

  # Firestore (for wallet, gifts, profiles, etc.)
  cloud_firestore: ^5.4.4

  # Firebase Authentication (for phone OTP login)
  firebase_auth: ^5.3.3

  # Voice chat SDK (Agora – for voice rooms)
  agora_rtc_engine: ^6.4.2

  # State management
  provider: ^6.1.2

  # Default Flutter icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/banner.png
    - assets/images/crown.png
    - assets/images/gift.png
    - assets/images/home.png
    - assets/images/mic.png
    - assets/images/profile.png
    - assets/images/rocket.png
    - assets/images/star.png
    - assets/images/wallet.png
    - assets/images/app_icon.png
