name: bigfun_voice
description: BigFun Voice Chat with all features working
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (compatible with Flutter 3.19)
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0

  # Voice Chat (Agora)
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.0.1

  # State Management & Utils
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2

  # UI
  flutter_svg: ^2.0.9
  cupertino_icons
