name: bigfun_voice
description: A new Flutter project for BigFun Voice Chat
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core (required for Firestore)
  firebase_core: ^3.6.0

  # Firestore (compatible with Flutter 3.24.3)
  cloud_firestore: ^5.4.4

  # Firebase Authentication (for phone OTP login if needed)
  firebase_auth: ^5.3.3

  # Voice chat SDK (example: Agora – replace if using another one)
  agora_rtc_engine: ^6.4.2

  # State management
  provider: ^6.1.2

  # Default Flutter icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
