name: iOS Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ios:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS (No Code Sign)
        run: |
          flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload
          zip -r app.ipa Payload

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: app.ipa
          retention-days: 30
